backend:
  name: github
  repo: Aayush-Thakkar/johaar2
  branch: main

media_folder: "assets/products"
public_folder: "/assets/products"

collections:
  - name: "products"
    label: "Products"
    label_singular: "Product"
    folder: "data/products"
    create: true
    delete: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Short Description", name: "desc", widget: "string", required: true}
      - {label: "Price (₹)", name: "price", widget: "number", required: true, value_type: "int"}
      - {label: "Tag", name: "tag", widget: "select", options: ["BEST SELLER", "WORKSTATION", "ULTRABOOK", "GAMING READY", "BUDGET PICK", "PREMIUM", "NEW ARRIVAL"], required: true}
      - {label: "Brand", name: "brand", widget: "string", required: true}
      - {label: "Condition", name: "condition", widget: "select", options: ["Refurbished", "New", "Used"], default: "Refurbished"}
      - {label: "Detailed Description", name: "details", widget: "text", required: true}
      - {label: "Image", name: "image", widget: "image", required: true}
      - {label: "Product ID", name: "id", widget: "number", required: true, value_type: "int"}
